=== miguelangel-jg/cineXML.github.io/cine.dtd
<!ELEMENT cine (peliculas, directores,actores,compositores)>
<!ELEMENT peliculas (pelicula+)>

<!-- Peliculas-->
<!ELEMENT pelicula (titulo,genero,a_estreno,reparto,director_pelicula,banda_sonora,productora,recaudacion, premios_pelicula)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT a_estreno (#PCDATA)>
<!ELEMENT reparto (principales,secundarios)>
<!ELEMENT principales (principal+)>
<!ELEMENT secundarios (secundario+)>
<!ELEMENT principal (#PCDATA)>
<!ELEMENT secundario (#PCDATA)>
<!ELEMENT director_pelicula (#PCDATA)>
<!ELEMENT banda_sonora (#PCDATA)>
<!ELEMENT productora (#PCDATA)>
<!ELEMENT recaudacion (#PCDATA)>
<!ELEMENT premios_pelicula (premio_pelicula+)>
<!ELEMENT premio_pelicula (categoria_premio,ganador_premio)>
<!ELEMENT categoria_premio (#PCDATA)>
<!ELEMENT ganador_premio (#PCDATA)>

<!-- Directores-->
<!ELEMENT directores (director+)>
<!ELEMENT director (nombre,obras,premios_director)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT obras (obra+)>
<!ELEMENT obra (#PCDATA)>
<!ELEMENT premios_director (premio_director+)>
<!ELEMENT premio_director (categoria,obra_ganadora)>
<!ELEMENT obra_ganadora (#PCDATA)>
<!ELEMENT categoria (#PCDATA)>

<!-- Actores -->
<!ELEMENT actores (actor+)>
<!ELEMENT actor (nombre,actuaciones,premios_actor)>
<!ELEMENT actuaciones (actuacion+)>
<!ELEMENT premios_actor (premio_actor+)>
<!ELEMENT premio_actor (categoria_actuacion, actuacion)>
<!ELEMENT categoria_actuacion (#PCDATA)>
<!ELEMENT actuacion (#PCDATA)>

<!-- Musicos-->
<!ELEMENT compositores (compositor+)>
<!ELEMENT compositor (nombre,peliculas_compuestas,premios_compositores)>
<!ELEMENT peliculas_compuestas (pelicula_compuesta+)>
<!ELEMENT pelicula_compuesta (#PCDATA)>
<!ELEMENT premios_compositores (premio_compositor+)>
<!ELEMENT premio_compositor (galardones,pelicula_premiada)>
<!ELEMENT galardones (#PCDATA)>
<!ELEMENT pelicula_premiada (#PCDATA)>

=== miguelangel-jg/cineXML.github.io/cine.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cine SYSTEM "cine.dtd">
<cine>
    <peliculas>
        <pelicula>
            <titulo>Oppenheimer</titulo>
            <genero>Biopic/Historica</genero>
            <a_estreno>2023</a_estreno>
            <reparto>
                <principales>
                    <principal>Cillian Murphy</principal>
                    <principal>Robert Downey Jr</principal>
                </principales>
                <secundarios>
                    <secundario>Emily Blunt</secundario>
                    <secundario>Florence Pugh</secundario>
                </secundarios>
            </reparto>
            <director_pelicula>Christopher Nolan</director_pelicula>
            <banda_sonora>Ludwig Goransson</banda_sonora>
            <productora>Universal Pictures</productora>
            <recaudacion>1000 millones</recaudacion>
            <premios_pelicula>
                <premio_pelicula>
                    <categoria_premio>Globo de Oro: Mejor Director</categoria_premio>
                    <ganador_premio>Christopher Nolan</ganador_premio>  
                </premio_pelicula>
                <premio_pelicula>
                    <categoria_premio>Globo de Oro: Mejor Actor</categoria_premio>
                    <ganador_premio>Cillian Murphy</ganador_premio>
                </premio_pelicula>
                <premio_pelicula>
                    <categoria_premio>Globo de Oro: Mejor Pelicula</categoria_premio>
                    <ganador_premio>Oppenheimer</ganador_premio>
                </premio_pelicula>
                <premio_pelicula>
                    <categoria_premio>Globo de Oro: Mejor actor de Reparto</categoria_premio>
                    <ganador_premio>Robert Downey Jr</ganador_premio>
                </premio_pelicula>
            </premios_pelicula>
        </pelicula>

        <pelicula>
            <titulo>Vengadores Endgame</titulo>
            <genero>Accion / Superheroes</genero>
            <a_estreno>2019</a_estreno>
            <reparto>
                <principales>
                    <principal>Chris Evans</principal>
                    <principal>Robert Downey Jr</principal>
                </principales>
                <secundarios>
                    <secundario>Tom Holland</secundario>
                    <secundario>Scarlett Johansson</secundario>
                </secundarios>
            </reparto>
            <director_pelicula>Anthony y Joe Russo</director_pelicula>
            <banda_sonora>Alan Silvestri</banda_sonora>
            <productora>Marvel Studios</productora>
            <recaudacion>2800 millones</recaudacion>
            <premios_pelicula>
                <premio_pelicula>
                    <categoria_premio>AVN Awards: Mejores Efectos Especiales</categoria_premio>
                    <ganador_premio>Anthony y Joe Russo</ganador_premio>
                </premio_pelicula>
            </premios_pelicula>
        </pelicula>

        <pelicula>
            <titulo>Forrest Gump</titulo>
            <genero>Drama</genero>
            <a_estreno>1994</a_estreno>
            <reparto>
                <principales>
                    <principal>Tom Hanks</principal>
                    <principal>Robin Wright</principal>
                </principales>
                <secundarios>
                    <secundario>Gary Sinise</secundario>
                    <secundario>Haley Joel Osment</secundario>
                </secundarios>
            </reparto>
            <director_pelicula>Robert Zemeckis</director_pelicula>
            <banda_sonora>Alan Silvestri</banda_sonora>
            <productora>Paramount Pictures</productora>
            <recaudacion>678 millones</recaudacion>
            <premios_pelicula>
                <premio_pelicula>
                    <categoria_premio>Oscar: Mejor Pelicula</categoria_premio>
                    <ganador_premio></ganador_premio>
                </premio_pelicula>
                <premio_pelicula>
                    <categoria_premio>Oscar: Mejor Actor</categoria_premio>
                    <ganador_premio>Tom Hanks</ganador_premio>
                </premio_pelicula>
                <premio_pelicula>
                    <categoria_premio>Oscar: Mejor Direccion</categoria_premio>
                    <ganador_premio>Robert Zemeckis</ganador_premio>
                </premio_pelicula>
            </premios_pelicula>
        </pelicula>
        <pelicula>
            <titulo>El caballero Oscuro</titulo>
            <genero>Accion/ Suerheroes</genero>
            <a_estreno>2008</a_estreno>
            <reparto>
                <principales>
                    <principal>Christian Bale</principal>
                    <principal>Heath Ledger</principal>
                </principales>
                <secundarios>
                    <secundario>Aaron Eckart</secundario>
                    <secundario>Michael Cane</secundario>
                </secundarios>
            </reparto>
            <director_pelicula>Christopher Nolan</director_pelicula>
            <banda_sonora>Hans Zimmer </banda_sonora>
            <productora>Warner Bros</productora>
            <recaudacion>1000 millones</recaudacion>
            <premios_pelicula>
                <premio_pelicula>
                    <categoria_premio>Oscar: Mejor Actor de Reparto</categoria_premio>
                    <ganador_premio>Heath Ledger</ganador_premio>
                </premio_pelicula>
            </premios_pelicula>
        </pelicula>

        <pelicula>
            <titulo>Pulp Fiction</titulo>
            <genero>Crimen / Suspenso</genero>
            <a_estreno>1995</a_estreno>
            <reparto>
                <principales>
                    <principal>Samuel L Jackson</principal>
                    <principal>John Travolta</principal>
                </principales>
                <secundarios>
                    <secundario>Bruce Willis</secundario>
                    <secundario>Uma Thurman</secundario>
                </secundarios>
            </reparto>
            <director_pelicula>Quentin Tarantino</director_pelicula>
            <banda_sonora>Quentin Tarantino</banda_sonora>
            <productora>Miramax</productora>
            <recaudacion>213 millones</recaudacion>
            <premios_pelicula>
                <premio_pelicula>
                    <categoria_premio>Globo de Oro: Mejor Guion</categoria_premio>
                    <ganador_premio>Quentin Tarantino</ganador_premio>
                </premio_pelicula>
            </premios_pelicula>
        </pelicula>

        <pelicula>
            <titulo>Django Desencadenado</titulo>
            <genero>Western</genero>
            <a_estreno>2012</a_estreno>
            <reparto>
                <principales>
                    <principal>Jamie Foxx</principal>
                    <principal>Leonardo Dicaprio</principal>
                </principales>
                <secundarios>
                    <secundario>Christoph Waltz</secundario>
                    <secundario>Samuel L Jackson</secundario>
                </secundarios>
            </reparto>
            <director_pelicula>Quentin Tarantino</director_pelicula>
            <banda_sonora>Ennio Morricone</banda_sonora>
            <productora>SONY PICTURES</productora>
            <recaudacion>426 millones</recaudacion>
            <premios_pelicula>
                <premio_pelicula>
                    <categoria_premio>Oscar: Mejor Guion</categoria_premio>
                    <ganador_premio>Quentin Tarantino</ganador_premio>
                </premio_pelicula>
                <premio_pelicula>
                    <categoria_premio>Oscar: Mejor Actor de Reparto</categoria_premio>
                    <ganador_premio>Christoph Waltz</ganador_premio>
                </premio_pelicula>
                <premio_pelicula>
                    <categoria_premio>Globo de Oro: Mejor Guion</categoria_premio>
                    <ganador_premio>Quentin Tarantino</ganador_premio>
                </premio_pelicula>
            </premios_pelicula>
        </pelicula>
            <pelicula>
                <titulo>Infiltrados</titulo>
                <genero>Crimen / Suspenso</genero>
                <a_estreno>2006</a_estreno>
                <reparto>
                    <principales>
                        <principal>Jack Nicholson</principal>
                        <principal>Leonardo Dicaprio</principal>
                    </principales>
                    <secundarios>
                        <secundario>Vera Farmiga</secundario>
                        <secundario>Matt Damon</secundario>
                    </secundarios>
                </reparto>
                <director_pelicula>Martin Scorsese</director_pelicula>
                <banda_sonora>Howard Shore</banda_sonora>
                <productora>Warner Bros</productora>
                <recaudacion>291 millones</recaudacion>
                <premios_pelicula>
                    <premio_pelicula>
                        <categoria_premio>Oscar: Mejor Direccion</categoria_premio>
                        <ganador_premio>Martin Scorsese</ganador_premio>
                    </premio_pelicula>
                    <premio_pelicula>
                        <categoria_premio>Oscar: Mejor Pelicula</categoria_premio>
                        <ganador_premio>Infiltrados</ganador_premio>
                    </premio_pelicula>
                    <premio_pelicula>
                        <categoria_premio>Globo de Oro: Mejor Direccion</categoria_premio>
                        <ganador_premio>Martin Scorsese</ganador_premio>
                    </premio_pelicula>
                </premios_pelicula>
